server.port=8290
spring.ai.mcp.server.enabled=false
spring.ai.mcp.client.enabled=true
spring.ai.mcp.client.type=SYNC
spring.ai.mcp.client.streamable-http.connections.training.url=http://localhost:8090
spring.ai.mcp.client.streamable-http.connections.training.endpoint=/mcp
