spring.ai.mcp.server.enabled=true
spring.ai.mcp.server.name=training-mcp-server
spring.ai.mcp.server.version=1.0.0
spring.ai.mcp.server.type=SYNC
spring.ai.mcp.server.protocol=STREAMABLE
spring.ai.mcp.server.annotation-scanner.enabled=true
spring.ai.mcp.client.enabled=false

spring.ai.model.chat=none
spring.ai.model.embedding=none
