<project xmlns="http://maven.apache.org/POM/4.0.0"><modelVersion>4.0.0</modelVersion><groupId>org.javacream.training.spring.ai</groupId><artifactId>spring-ai-uebungen</artifactId><version>1.0.0</version><packaging>pom</packaging><modules><module>01-ChatClient</module><module>02-Advisors</module><module>03-Prompts</module><module>04-ResponseMetadata</module><module>05-StructuredOutput</module><module>06-Multimodality</module><module>07-Models</module><module>08-ChatMemory</module><module>09-ToolCalling</module><module>10-MCP</module><module>11-RAG</module><module>12-Evaluation</module><module>13-VectorStores</module><module>14-Observability</module><module>15-DevelopmentServices</module><module>16-Testcontainers</module></modules></project>